/* 初期データ。エディタで編集したものは保存先 (クラウド or この端末) にあり、こちらより優先される */
var RB_DEFAULT_DATA = {
  version: 2,
  meta: { title: 'ルーレットバトル' },
  rules: {
    hpScalePerPlayer: 15, protect: 'lastStand', orderBy: 'speed', maxSpinChain: 2, maxExtraSpins: 2,
    aoeFalloff: 6, aoeFloor: 50, suddenDeathRound: 8, suddenDeathPct: 25, maxRounds: 60,
    dotLabel: '●', starLabel: '★', itemMode: 'random',
  },

  elements: [
    { id: 'fire',    name: '炎', icon: '🔥', color: '#ff6a3d' },
    { id: 'water',   name: '水', icon: '💧', color: '#3d9bff' },
    { id: 'grass',   name: '草', icon: '🌿', color: '#4cc66a' },
    { id: 'thunder', name: '雷', icon: '⚡', color: '#f5c518' },
    { id: 'light',   name: '光', icon: '✨', color: '#ffe08a' },
    { id: 'dark',    name: '闇', icon: '🌑', color: '#9a6cff' },
    { id: 'earth',   name: '地', icon: '🪨', color: '#c49a5a' },
    { id: 'wind',    name: '風', icon: '🌪', color: '#8fe3c0' },
    { id: 'psychic', name: '念', icon: '🔮', color: '#ff7ad9' },
  ],
  // 属性は「技ごとの追加威力 (elemBonus)」で表現する。相性倍率表は使わない
  chart: {},

  types: [
    { id: 'attacker', name: 'アタッカー',   desc: '攻撃力+15% / HP-10%', atkPct: 15, hpPct: -10 },
    { id: 'defender', name: 'ディフェンダー', desc: 'HP+15% / 被ダメ-2 / 攻撃力-10%', hpPct: 15, defFlat: 2, atkPct: -10 },
    { id: 'trickster', name: 'トリックスター', desc: '相手を状態異常にする確率+15%', statusChanceBonus: 15 },
    { id: 'healer',   name: 'ヒーラー',     desc: '回復量+10% / HP+5%', healPct: 10, hpPct: 5 },
    { id: 'balance',  name: 'バランス',     desc: 'HP+5% / 攻撃力+5%', hpPct: 5, atkPct: 5 },
    { id: 'gambler',  name: 'ギャンブラー', desc: '大波乱担当。HP+10%', hpPct: 10 },
  ],

  statuses: [
    { id: 'para',    name: 'まひ',   icon: '⚡', color: '#f5c518', turns: 2, disableCount: 1, disableMode: 'random', desc: 'ルーレットの技が1つ使えなくなる (止まると不発)' },
    { id: 'sleep',   name: 'ねむり', icon: '💤', color: '#9aa7c7', turns: 2, skipWake: 40, desc: 'ターン開始時に目覚めルーレット (40%)。起きれば行動できる' },
    { id: 'freeze',  name: 'こおり', icon: '🧊', color: '#7fd8ff', turns: 2, skipWake: 50, cureOnHit: true, desc: 'ターン開始時に解凍ルーレット (50%)。攻撃を受けると解ける' },
    { id: 'poison',  name: 'どく',   icon: '☠', color: '#b05cf0', turns: 3, dotAmount: 10, desc: 'ターン終了時に10ダメージ' },
    { id: 'burn',    name: 'やけど', icon: '♨', color: '#ff6a3d', turns: 3, dotAmount: 6, atkPct: -25, desc: 'ターン終了時に6ダメージ・攻撃力-25%' },
    { id: 'confuse', name: 'こんらん', icon: '😵', color: '#ff8ad8', turns: 2, confuseChance: 40, desc: '40%で狙いがランダム (自分含む) になる' },
    { id: 'future',  name: '未来予知', icon: '🔮', color: '#ff7ad9', turns: 2, expireDamage: 55, desc: '2ターン後 (持ち主のターン終わり) に念の力で55ダメージ' },
    { id: 'bomb',    name: 'ばくだん', icon: '💣', color: '#ff9340', turns: 3, expireDamage: 60, desc: '3ターン後 (持ち主のターン終わり) に爆発して60ダメージ。「ばくだんパス」で押し付けられる' },
  ],

  moves: [
    { id: 'miss', name: 'ミス', kind: 'miss', desc: '何も起きない' },
    // --- 炎
    { id: 'hinoko', name: 'ファイアショット', kind: 'attack', power: 35, target: 'single', elemBonus: { grass: 15, wind: 10 }, typeBonus: { healer: 15 } },
    { id: 'flareblast', name: '紅蓮突撃', kind: 'attack', power: 60, target: 'single', recoilPct: 20, elemBonus: { grass: 20, wind: 10 }, typeBonus: { healer: 15 } },
    { id: 'neppu', name: '熱波', kind: 'attack', power: 22, target: 'allEnemies', elemBonus: { grass: 10, wind: 5 }, typeBonus: { healer: 10 }, effects: [{ type: 'status', to: 'target', status: 'burn', chance: 20 }] },
    { id: 'hoeru', name: '雄たけび', kind: 'status', target: 'self', effects: [{ type: 'mod', to: 'self', stat: 'atkFlat', value: 10, turns: 2 }] },
    { id: 'onibi', name: '焦熱の呪い', kind: 'status', target: 'single', effects: [{ type: 'status', to: 'target', status: 'burn' }] },
    { id: 'kaenguruma', name: '火輪蹴り', kind: 'attack', power: 45, target: 'single', elemBonus: { grass: 15, wind: 10 }, typeBonus: { defender: 15 } },
    { id: 'madowashi', name: '幻炎', kind: 'attack', power: 25, target: 'single', elemBonus: { grass: 15, wind: 10 }, typeBonus: { defender: 15 }, effects: [{ type: 'status', to: 'target', status: 'confuse', chance: 60 }] },
    { id: 'youko', name: '狐火の舞', kind: 'status', target: 'self', effects: [{ type: 'mod', to: 'self', stat: 'atkPct', value: 20, turns: 2 }, { type: 'spinAgain' }] },
    // --- 水
    { id: 'mizudeppo', name: 'アクアショット', kind: 'attack', power: 30, target: 'single', elemBonus: { fire: 15, earth: 10 }, typeBonus: { trickster: 15 } },
    { id: 'shizuku', name: 'ヒールドロップ', kind: 'heal', target: 'self', effects: [{ type: 'heal', to: 'self', amount: 22 }] },
    { id: 'bubbleshield', name: 'バブルシールド', kind: 'guard', target: 'self', effects: [{ type: 'mod', to: 'self', stat: 'barrier', value: 25, turns: 3 }], desc: '20ダメージまで吸収するバリア (3ターン)' },
    { id: 'dakuryu', name: '大激流', kind: 'attack', power: 20, target: 'allEnemies', elemBonus: { fire: 10, earth: 5 }, typeBonus: { trickster: 10 } },
    { id: 'hydrocannon', name: '渦潮砲', kind: 'attack', power: 55, target: 'single', elemBonus: { fire: 20, earth: 15 }, typeBonus: { attacker: 15 } },
    { id: 'karani', name: 'シェルガード', kind: 'guard', target: 'self', effects: [{ type: 'mod', to: 'self', stat: 'guard', value: 1, turns: 2 }, { type: 'mod', to: 'self', stat: 'defFlat', value: 5, turns: 2 }] },
    { id: 'noshikakari', name: 'ヘビープレス', kind: 'attack', power: 30, target: 'single', elemBonus: { fire: 15, earth: 10 }, typeBonus: { attacker: 15 }, effects: [{ type: 'status', to: 'target', status: 'para', chance: 30 }] },
    { id: 'reitobeam', name: '氷結光線', kind: 'attack', power: 35, target: 'single', elemBonus: { grass: 15, earth: 10 }, typeBonus: { attacker: 15 }, effects: [{ type: 'status', to: 'target', status: 'freeze', chance: 20 }] },
    // --- 草
    { id: 'tsurunomuchi', name: 'ツタ鞭', kind: 'attack', power: 30, target: 'single', elemBonus: { water: 15, earth: 10 }, typeBonus: { attacker: 15 } },
    { id: 'yadorigi', name: '吸精の種', kind: 'attack', power: 20, target: 'single', drainPct: 40, elemBonus: { water: 10, earth: 10 }, typeBonus: { attacker: 15 } },
    { id: 'nemurigona', name: '眠り花粉', kind: 'status', target: 'single', effects: [{ type: 'status', to: 'target', status: 'sleep', chance: 60 }] },
    { id: 'woodhammer', name: '大樹の鉄槌', kind: 'attack', power: 55, target: 'single', recoilPct: 25, elemBonus: { water: 20, earth: 15 }, typeBonus: { attacker: 15 } },
    { id: 'dokunokona', name: '毒の胞子', kind: 'status', target: 'single', effects: [{ type: 'status', to: 'target', status: 'poison' }] },
    { id: 'hanafubuki', name: '桜吹雪', kind: 'attack', power: 35, target: 'allEnemies', elemBonus: { water: 10, earth: 5 }, typeBonus: { defender: 10 } },
    { id: 'amaikaori', name: '甘い誘惑', kind: 'status', target: 'single', effects: [{ type: 'mod', to: 'target', stat: 'atkPct', value: -30, turns: 2 }] },
    { id: 'hanabira', name: '花乱舞', kind: 'attack', power: 55, target: 'single', elemBonus: { water: 15, earth: 10 }, typeBonus: { defender: 15 }, effects: [{ type: 'status', to: 'self', status: 'confuse', chance: 50 }] },
    // --- 雷
    { id: 'denkishock', name: 'スパークショット', kind: 'attack', power: 35, target: 'single', elemBonus: { water: 15, wind: 15 }, typeBonus: { defender: 15 }, effects: [{ type: 'status', to: 'target', status: 'para', chance: 30 }] },
    { id: 'houden', name: 'サンダーバースト', kind: 'attack', power: 20, target: 'allEnemies', elemBonus: { water: 10, wind: 10 }, typeBonus: { defender: 10 }, effects: [{ type: 'status', to: 'target', status: 'para', chance: 20 }] },
    { id: 'kousoku', name: '加速ダッシュ', kind: 'status', target: 'self', effects: [{ type: 'spinAgain' }] },
    { id: 'kaminari', name: '落雷', kind: 'attack', power: 70, target: 'single', elemBonus: { water: 25, wind: 20 }, typeBonus: { defender: 15 } },
    { id: 'wildvolt', name: '迅雷突進', kind: 'attack', power: 60, target: 'single', recoilPct: 20, elemBonus: { water: 20, wind: 10 }, typeBonus: { defender: 20 } },
    { id: 'kaminarinokiba', name: '雷牙', kind: 'attack', power: 45, target: 'single', elemBonus: { water: 15, wind: 10 }, typeBonus: { healer: 15 }, effects: [{ type: 'status', to: 'target', status: 'para', chance: 20 }] },
    { id: 'juden', name: '蓄電', kind: 'status', target: 'self', effects: [{ type: 'mod', to: 'self', stat: 'atkPct', value: 50, turns: 2 }] },
    // --- 光
    { id: 'hikarinoya', name: 'ライトアロー', kind: 'attack', power: 30, target: 'single', elemBonus: { dark: 15, psychic: 10 }, typeBonus: { trickster: 15 } },
    { id: 'iyashinohikari', name: 'ホーリーヒール', kind: 'heal', target: 'self', effects: [{ type: 'heal', to: 'self', amount: 30 }, { type: 'cure', to: 'self' }] },
    { id: 'holyray', name: 'ホーリーレイ', kind: 'attack', power: 45, target: 'single', elemBonus: { dark: 20, psychic: 10 }, typeBonus: { trickster: 15 } },
    { id: 'seiiki', name: 'せいいき', kind: 'guard', target: 'self', effects: [{ type: 'mod', to: 'self', stat: 'nullifyBelow', value: 20, turns: 2 }] },
    { id: 'seiken', name: 'せいけん', kind: 'attack', power: 35, target: 'single', markBonus: { dot: 15 }, elemBonus: { dark: 10, psychic: 10 }, typeBonus: { trickster: 15, gambler: 15 } },
    { id: 'iatsu', name: 'いあつ', kind: 'status', target: 'group', groupMark: 'dot', effects: [{ type: 'status', to: 'target', status: 'para', chance: 40 }], desc: '敵の●全員を40%でまひさせる' },
    { id: 'mikiri', name: '受け流し', kind: 'guard', target: 'self', effects: [{ type: 'mod', to: 'self', stat: 'guard', value: 1, turns: 2 }] },
    { id: 'gigaslash', name: '断罪の一閃', kind: 'attack', power: 50, target: 'single', elemBonus: { dark: 10, psychic: 10 }, typeBonus: { attacker: 15 } },
    // --- 闇
    { id: 'shadowclaw', name: '影爪', kind: 'attack', power: 35, target: 'single', elemBonus: { light: 15, psychic: 10 }, typeBonus: { healer: 15 } },
    { id: 'nightburst', name: '闇夜連撃', kind: 'attack', power: 20, hits: 2, target: 'single', elemBonus: { light: 8, psychic: 10 }, typeBonus: { healer: 15 } },
    { id: 'akumu', name: '悪夢の囁き', kind: 'attack', power: 20, target: 'single', elemBonus: { light: 10, psychic: 10 }, typeBonus: { healer: 15 }, effects: [{ type: 'status', to: 'target', status: 'sleep', chance: 30 }] },
    { id: 'yumekui', name: '夢喰らい', kind: 'attack', power: 30, target: 'single', elemBonus: { light: 15, psychic: 10 }, typeBonus: { healer: 15 }, drainPct: 50, effects: [{ type: 'damage', to: 'target', power: 20, drainPct: 50, cond: { targetStatus: 'sleep' } }] },
    { id: 'ayashiihikari', name: '惑わしの灯', kind: 'status', target: 'single', effects: [{ type: 'status', to: 'target', status: 'confuse' }] },
    { id: 'shadowball', name: '暗黒弾', kind: 'attack', power: 50, target: 'single', elemBonus: { light: 15, psychic: 15 }, typeBonus: { defender: 15 } },
    { id: 'noroi', name: '呪詛', kind: 'status', target: 'single', effects: [{ type: 'damage', to: 'self', power: 10 }, { type: 'mod', to: 'target', stat: 'dmgTakenPct', value: 30, turns: 3 }] },
    { id: 'kagebunshin', name: '影武者', kind: 'guard', target: 'self', effects: [{ type: 'mod', to: 'self', stat: 'guard', value: 1, turns: 2 }, { type: 'spinAgain', chance: 50 }] },

    // ===== ここからパーティ向けの変わり種 =====
    // ポンコツ: ミスで強くなる
    { id: 'yakekuso', name: 'やけくそビーム', kind: 'attack', power: 10, target: 'single', scaleBy: 'misses', scalePer: 10, scaleMax: 90, elemBonus: { water: 10, wind: 10 }, typeBonus: { gambler: 15 }, desc: '威力10 + これまでにミスを引いた回数×10 (最大+90)' },
    { id: 'garakuta', name: 'ガラクタなげ', kind: 'attack', power: 30, target: 'randomEnemy', elemBonus: { water: 15, wind: 10 }, typeBonus: { gambler: 15 }, desc: 'ランダムな敵に投げつける' },
    { id: 'overheat', name: 'オーバーロード', kind: 'attack', power: 40, target: 'everyone', elemBonus: { water: 10, wind: 5 }, typeBonus: { gambler: 10 }, desc: '自分も含む全員にダメージ' },
    { id: 'shuuri', name: '自己修理', kind: 'heal', target: 'self', effects: [{ type: 'heal', to: 'self', amount: 30 }, { type: 'cure', to: 'self' }] },
    // ミミック: ランダム・コピー
    { id: 'yubiwofuru', name: '気まぐれタクト', kind: 'special', target: 'single', effects: [{ type: 'randomMove', pool: 'all' }], desc: 'ゲームに登場するすべての技からランダムに1つ使う' },
    { id: 'monomane', name: 'コピーキャット', kind: 'special', target: 'single', effects: [{ type: 'mimic' }], desc: '選んだ相手が最後に使った技をまねする' },
    { id: 'odorokasu', name: 'びっくり箱', kind: 'attack', power: 30, target: 'single', elemBonus: { light: 10, psychic: 10 }, typeBonus: { healer: 15, defender: 15 }, effects: [{ type: 'status', to: 'target', status: 'confuse', chance: 30 }] },
    // ダイス: ギャンブル・大逆転
    { id: 'allin', name: 'オールイン', kind: 'special', target: 'single', effects: [{ type: 'damage', to: 'target', power: 90, chance: 50 }, { type: 'damage', to: 'self', power: 25, link: 'else' }], desc: '50%で相手に威力90! 外れたら自分が25ダメージ' },
    { id: 'daigyakuten', name: '大逆転ルーレット', kind: 'special', target: 'self', effects: [{ type: 'hpChaos', mode: 'shuffle' }], desc: '生きている全員のHP割合をシャッフル! (大波乱)' },
    { id: 'luckycoin', name: 'ラッキーコイン', kind: 'status', target: 'self', effects: [{ type: 'mod', to: 'self', stat: 'luck', value: 2, turns: 0 }, { type: 'spinAgain' }], desc: 'ミスを2回まで引き直せるようになり、もう一回' },
    { id: 'diceshot', name: 'ダイスショット', kind: 'attack', power: 18, hits: 3, target: 'single', elemBonus: { dark: 5, psychic: 10 }, typeBonus: { balance: 15 }, desc: '3回攻撃' },
    // クロノ: 2回行動・時間
    { id: 'timeaccel', name: 'タイムアクセル', kind: 'status', target: 'self', effects: [{ type: 'mod', to: 'self', stat: 'extraSpins', value: 1, turns: 2 }], desc: '次の自分のターンから2ターンの間、2回行動' },
    { id: 'jikandorobo', name: 'じかんどろぼう', kind: 'special', target: 'single', effects: [{ type: 'damage', to: 'target', power: 25 }, { type: 'stealMods', to: 'target' }], desc: '25ダメージを与え、相手のバフを奪う' },
    { id: 'tokiwotomeru', name: 'ときをとめる', kind: 'status', target: 'single', effects: [{ type: 'status', to: 'target', status: 'freeze' }], desc: '相手をこおりにする' },
    { id: 'chikutaku', name: 'チクタクパンチ', kind: 'attack', power: 40, target: 'single', elemBonus: { fire: 15, earth: 10 }, typeBonus: { gambler: 15 } },
    // ボマー: 時限爆弾
    { id: 'bombset', name: 'ばくだんセット', kind: 'status', target: 'single', color: '#ff9340', effects: [{ type: 'status', to: 'target', status: 'bomb' }], desc: '相手にばくだん (3ターン後に60ダメージ) を仕掛ける' },
    { id: 'bombpass', name: 'ばくだんパス', kind: 'special', target: 'single', effects: [{ type: 'transferStatus', to: 'target' }, { type: 'status', to: 'target', status: 'bomb', turns: 2, link: 'else' }], desc: '自分の状態異常をすべて相手に押し付ける。押し付けるものが無ければ、2ターンで爆発するばくだんを渡す' },
    { id: 'daibakuhatsu', name: 'ドカン大爆破', kind: 'attack', power: 50, target: 'allEnemies', elemBonus: { grass: 10, wind: 5 }, typeBonus: { defender: 10 }, effects: [{ type: 'damage', to: 'self', power: 25 }], desc: '敵全体を巻き込む大爆発。自分も25ダメージ' },
    { id: 'hibana', name: 'ひばな', kind: 'attack', power: 40, target: 'single', elemBonus: { grass: 15, wind: 10 }, typeBonus: { defender: 15 } },
    // リュウ: ため・成長
    { id: 'tamepunch', name: 'ためパンチ', kind: 'attack', power: 20, target: 'single', scaleBy: 'uses', scalePer: 12, scaleMax: 72, elemBonus: { water: 10, earth: 10 }, typeBonus: { healer: 15 }, desc: '使うたびに威力+12 (最大+72)。次回以降どんどん強くなる' },
    { id: 'kiaidame', name: '集中', kind: 'status', target: 'self', effects: [{ type: 'mod', to: 'self', stat: 'nextPower', value: 40, turns: 0 }], desc: '次の攻撃の威力+40' },
    { id: 'hissatsu', name: 'ひっさつけん', kind: 'attack', power: 50, target: 'single', elemBonus: { water: 15, earth: 10 }, typeBonus: { defender: 25 } },
    // ジョーカー: あべこべ・入れ替え・反射
    { id: 'abekobe', name: 'あべこべ', kind: 'special', target: 'single', effects: [{ type: 'invertMods', to: 'target' }, { type: 'damage', to: 'target', power: 20, link: 'else' }], desc: '相手のバフとデバフを逆にする。何もなければ20ダメージ' },
    { id: 'surikae', name: '入れ替えマジック', kind: 'special', target: 'single', effects: [{ type: 'hpSwap', to: 'target' }], desc: '相手とHP割合を入れ替える' },
    { id: 'mirrorcoat', name: '鏡の盾', kind: 'guard', target: 'self', effects: [{ type: 'mod', to: 'self', stat: 'reflectPct', value: 60, turns: 2 }], desc: '2ターン、受けたダメージの60%を跳ね返す' },
    { id: 'trumpnage', name: 'トランプなげ', kind: 'attack', power: 16, hits: 3, target: 'single', elemBonus: { light: 5, psychic: 10 }, typeBonus: { defender: 15 }, desc: '3回攻撃' },

    // ===== 全体攻撃 (テンポ用) =====
    { id: 'kitsunebi', name: '狐火', kind: 'attack', power: 20, target: 'allEnemies', elemBonus: { grass: 10, wind: 5 }, typeBonus: { defender: 10 }, effects: [{ type: 'status', to: 'target', status: 'burn', chance: 15 }] },
    { id: 'naminori', name: '大津波', kind: 'attack', power: 25, target: 'allEnemies', elemBonus: { fire: 10, earth: 10 }, typeBonus: { attacker: 10 } },
    { id: 'happacutter', name: '木の葉嵐', kind: 'attack', power: 20, target: 'allEnemies', elemBonus: { water: 10, earth: 10 }, typeBonus: { attacker: 10 } },
    { id: 'flash', name: '閃光', kind: 'attack', power: 20, target: 'allEnemies', elemBonus: { dark: 10, psychic: 5 }, typeBonus: { trickster: 10 } },
    { id: 'koumorinomure', name: 'こうもりのむれ', kind: 'attack', power: 20, target: 'allEnemies', drainPct: 0, elemBonus: { light: 10, psychic: 10 }, typeBonus: { healer: 10 } },
    { id: 'ghostparade', name: 'ゴーストパレード', kind: 'attack', power: 25, target: 'allEnemies', elemBonus: { light: 10, psychic: 5 }, typeBonus: { defender: 10 }, effects: [{ type: 'status', to: 'target', status: 'confuse', chance: 15 }] },
    { id: 'timewave', name: 'タイムウェーブ', kind: 'attack', power: 25, target: 'allEnemies', elemBonus: { fire: 10, earth: 5 }, typeBonus: { gambler: 10 } },
    { id: 'cardshower', name: 'カードシャワー', kind: 'attack', power: 25, target: 'allEnemies', elemBonus: { light: 10, psychic: 5 }, typeBonus: { defender: 10 } },
    { id: 'baramakidice', name: 'ばらまきダイス', kind: 'attack', power: 25, target: 'allEnemies', elemBonus: { dark: 10, psychic: 5 }, typeBonus: { balance: 10 } },

    // ===== ●/★ を狙う技 (バトエン風「●に30ダメージ」) =====
    { id: 'marunomi', name: 'まるのみ', kind: 'attack', power: 30, target: 'group', elemBonus: { light: 10, psychic: 5 }, typeBonus: { defender: 10 }, groupMark: 'dot', desc: '敵の●全員に30ダメージ' },
    { id: 'raimei', name: 'らいめい', kind: 'attack', power: 30, target: 'group', groupMark: 'star', elemBonus: { water: 10, wind: 5 }, typeBonus: { healer: 10 }, desc: '敵の★全員に30ダメージ' },
    { id: 'hoshikudaki', name: 'ほしくだき', kind: 'attack', power: 30, target: 'group', elemBonus: { water: 10, earth: 5 }, typeBonus: { healer: 10 }, groupMark: 'star', desc: '敵の★全員に30ダメージ' },
    // ===== 進化 =====
    { id: 'taiatari', name: '突進', kind: 'attack', power: 25, target: 'single' },
    { id: 'shinka', name: '覚醒', kind: 'special', target: 'self', color: '#8ff0ff', effects: [{ type: 'transform', to: 'self', char: 'dragoon' }, { type: 'heal', to: 'self', amount: 25 }], desc: 'ドラグーンに進化してHP20回復 (ルーレットが変わる)' },
    { id: 'ryunoibuki', name: '竜の咆哮', kind: 'attack', power: 30, target: 'allEnemies', elemBonus: { grass: 10, wind: 5 }, typeBonus: { healer: 10 }, effects: [{ type: 'status', to: 'target', status: 'para', chance: 15 }] },
    { id: 'dragonclaw', name: '竜爪撃', kind: 'attack', power: 50, target: 'single', elemBonus: { grass: 15, wind: 10 }, typeBonus: { healer: 15 }, markBonus: { star: 15 } },
    { id: 'flaredrive', name: '紅蓮ダイブ', kind: 'attack', power: 75, target: 'single', recoilPct: 25, elemBonus: { grass: 20, wind: 10 }, typeBonus: { healer: 15 } },

    // ===== ギア用の技 (ギアのルーレットで毎ターン出る。ランダム技には出ない) =====
    { id: 'g_punch', name: 'ギアパンチ', kind: 'attack', power: 20, target: 'single', noRandom: true },
    { id: 'g_charge', name: 'パワーチャージ', kind: 'status', target: 'self', noRandom: true, effects: [{ type: 'mod', to: 'self', stat: 'atkFlat', value: 5, turns: 0 }], desc: '攻撃力+5 (永続・重なる)' },
    { id: 'g_heal', name: 'ヒールパルス', kind: 'heal', target: 'self', noRandom: true, effects: [{ type: 'heal', to: 'self', amount: 20 }] },
    { id: 'g_shield', name: 'シールド展開', kind: 'guard', target: 'self', noRandom: true, effects: [{ type: 'mod', to: 'self', stat: 'barrier', value: 20, turns: 2 }] },
    { id: 'g_storm', name: 'ギアストーム', kind: 'attack', power: 15, target: 'allEnemies', noRandom: true },
    { id: 'g_poison', name: 'どくがまわる', kind: 'status', target: 'self', noRandom: true, color: '#b05cf0', effects: [{ type: 'damage', to: 'self', power: 12 }], desc: '自分に12ダメージ' },
    { id: 'g_poison2', name: '猛毒', kind: 'status', target: 'self', noRandom: true, color: '#8a3cc0', effects: [{ type: 'damage', to: 'self', power: 25 }], desc: '自分に25ダメージ' },
    { id: 'g_doze', name: 'うとうと', kind: 'status', target: 'self', noRandom: true, color: '#9aa7c7', effects: [{ type: 'status', to: 'self', status: 'sleep', turns: 1 }], desc: '自分がねむり (1ターン)' },
    { id: 'g_rust', name: 'さびつく', kind: 'status', target: 'self', noRandom: true, color: '#b07a4a', effects: [{ type: 'mod', to: 'self', stat: 'atkPct', value: -20, turns: 2 }], desc: '自分の攻撃力-20% (2ターン)' },
    { id: 'g_nothing', name: 'セーフ', kind: 'miss', noRandom: true, color: '#6a7090', desc: '何も起きない' },
    // ===== きりふだ用の技 (1試合に1回だけ使える強力な技) =====
    { id: 'k_fullheal', name: 'だいかいふく', kind: 'heal', target: 'self', noRandom: true, effects: [{ type: 'heal', to: 'self', pct: 55 }, { type: 'cure', to: 'self' }], desc: '最大HPの50%回復・状態異常回復' },
    { id: 'k_meteor', name: 'メテオ', kind: 'attack', power: 45, target: 'allEnemies', noRandom: true, desc: '敵全体に45' },
    { id: 'k_finisher', name: 'ひっさつ', kind: 'attack', power: 90, target: 'single', noRandom: true, pierce: true, desc: '威力90・バリアやガードを貫通' },
    { id: 'k_fortress', name: 'てっぺき', kind: 'guard', target: 'self', noRandom: true, effects: [{ type: 'mod', to: 'self', stat: 'guard', value: 2, turns: 3 }, { type: 'heal', to: 'self', amount: 25 }], desc: '攻撃を2回無効 (3ターン)・HP20回復' },
    { id: 'k_chaos', name: 'だいどんでん', kind: 'special', target: 'self', noRandom: true, effects: [{ type: 'hpChaos', mode: 'shuffle' }], desc: '全員のHP割合をシャッフル' },
    { id: 'k_average', name: 'きんとうわり', kind: 'special', target: 'self', noRandom: true, effects: [{ type: 'hpChaos', mode: 'average' }], desc: '全員のHP割合を平均にそろえる' },
    { id: 'k_timestop', name: 'タイムストップ', kind: 'status', target: 'self', noRandom: true, effects: [{ type: 'mod', to: 'self', stat: 'extraSpins', value: 1, turns: 2 }, { type: 'spinAgain' }], desc: 'もう一回 + 次の2ターン2回行動' },
    { id: 'k_goodgear', name: 'ギア支給', kind: 'status', target: 'self', noRandom: true, effects: [{ type: 'removeGear', to: 'self' }, { type: 'attachGear', to: 'self', pool: 'good' }, { type: 'spinAgain' }], desc: '今のギアを外して良いギアをつけ、もう一回' },
    { id: 'k_curseall', name: 'のろいのばらまき', kind: 'special', target: 'allEnemies', noRandom: true, effects: [{ type: 'attachGear', to: 'target', pool: 'bad' }], desc: 'ギアのない敵全員に悪いギアをつける' },
    // ===== メカニック (ギア使い) =====
    { id: 'gearup', name: 'ギアそうちゃく', kind: 'status', target: 'self', effects: [{ type: 'attachGear', to: 'self', pool: 'good' }, { type: 'spinAgain', link: 'then' }], desc: '自分に良いギアをつけてもう一回 (ギアがあれば不発)' },
    { id: 'gearcurse', name: 'ポンコツギア', kind: 'status', target: 'single', effects: [{ type: 'attachGear', to: 'target', pool: 'bad' }, { type: 'damage', to: 'target', power: 25, link: 'else' }], desc: '相手に悪いギアをつける。もうギアがあれば25ダメージ' },
    { id: 'spanner', name: 'スパナなげ', kind: 'attack', power: 30, target: 'single', elemBonus: { water: 15, wind: 10 }, typeBonus: { defender: 15 } },
    { id: 'gearbreak', name: 'ギアクラッシュ', kind: 'attack', power: 25, target: 'allEnemies', elemBonus: { water: 10, wind: 5 }, typeBonus: { defender: 10 }, effects: [{ type: 'removeGear', to: 'target', chance: 50 }], desc: '敵全体に25。50%で相手のギアを壊す' },

    // ===== 新キャラの技 =====
    // ガンセキ (地・かたい岩)
    { id: 'rakuseki', name: '落石', kind: 'attack', power: 30, target: 'single', elemBonus: { thunder: 15, fire: 10 }, typeBonus: { attacker: 15 } },
    { id: 'jiware', name: '地割れ', kind: 'attack', power: 20, target: 'allEnemies', elemBonus: { thunder: 10, fire: 5 }, typeBonus: { attacker: 10 } },
    { id: 'korogari', name: '転がり', kind: 'attack', power: 15, target: 'single', elemBonus: { thunder: 15, fire: 10 }, typeBonus: { attacker: 15 }, scaleBy: 'uses', scalePer: 15, scaleMax: 60, desc: '使うたびに威力+15 (最大+60)' },
    { id: 'iwakamae', name: '岩の構え', kind: 'guard', target: 'self', effects: [{ type: 'mod', to: 'self', stat: 'defFlat', value: 10, turns: 2 }, { type: 'mod', to: 'self', stat: 'taunt', value: 1, turns: 2 }], desc: '2ターン被ダメ-10。挑発して敵の狙いを自分に集める' },
    // モゾ → サナギン → ヒラリス (虫の3段進化)
    { id: 'itohaki', name: '糸からめ', kind: 'status', target: 'single', effects: [{ type: 'mod', to: 'target', stat: 'missWeightPct', value: 60, turns: 2 }, { type: 'mod', to: 'target', stat: 'speed', value: -2, turns: 3 }], desc: '相手のミスの区画が60%大きくなり (2ターン)、すばやさ-2 (3ターン)' },
    { id: 'kajiru', name: 'かじりつき', kind: 'attack', power: 25, target: 'single', elemBonus: { water: 10, earth: 10 }, typeBonus: { gambler: 15 } },
    { id: 'dappi', name: '脱皮', kind: 'special', target: 'self', color: '#8ff0ff', effects: [{ type: 'transform', to: 'self', char: 'saNagin' }, { type: 'heal', to: 'self', amount: 20 }], desc: 'サナギンに進化 (HP15回復)' },
    { id: 'katakunaru', name: '硬くなる', kind: 'guard', target: 'self', effects: [{ type: 'mod', to: 'self', stat: 'defFlat', value: 15, turns: 2 }, { type: 'mod', to: 'self', stat: 'endure', value: 1, turns: 0 }], desc: '2ターン被ダメ-15。倒れそうな攻撃を1回こらえる' },
    { id: 'jittotaeru', name: 'じっと耐える', kind: 'heal', target: 'self', effects: [{ type: 'heal', to: 'self', amount: 20 }, { type: 'mod', to: 'self', stat: 'regen', value: 6, turns: 3 }], desc: 'HP15回復・3ターンの間 毎ターン6回復' },
    { id: 'uka', name: '羽化', kind: 'special', target: 'self', color: '#8ff0ff', effects: [{ type: 'transform', to: 'self', char: 'hirarisu' }, { type: 'heal', to: 'self', amount: 20 }, { type: 'spinAgain' }], desc: 'ヒラリスに進化 (HP15回復)・もう一回' },
    { id: 'rinpunstorm', name: '鱗粉の嵐', kind: 'attack', power: 22, target: 'allEnemies', elemBonus: { grass: 10, psychic: 5 }, typeBonus: { defender: 10 }, effects: [{ type: 'status', to: 'target', status: 'sleep', chance: 15 }], desc: '敵全体。15%でねむり' },
    { id: 'kazenomai', name: '風の舞', kind: 'status', target: 'self', effects: [{ type: 'mod', to: 'self', stat: 'evadePct', value: 20, turns: 2 }, { type: 'spinAgain' }], desc: '2ターン回避率+20%・もう一回' },
    { id: 'kyumitsu', name: '吸蜜', kind: 'attack', power: 30, target: 'single', drainPct: 30, elemBonus: { grass: 10, psychic: 10 }, typeBonus: { defender: 15 } },
    // ピチピチ → リヴァイア (弱い魚が大化けする)
    { id: 'haneru', name: '跳ねるだけ', kind: 'miss', color: '#6a7090', desc: 'ぴちぴち跳ねる。何も起きない' },
    { id: 'daikakusei', name: '大覚醒', kind: 'special', target: 'self', color: '#8ff0ff', effects: [{ type: 'transform', to: 'self', char: 'riviah' }, { type: 'heal', to: 'self', pct: 35 }], desc: 'リヴァイアに大化けし、最大HPの30%回復' },
    { id: 'ouzu', name: '大渦', kind: 'attack', power: 35, target: 'allEnemies', elemBonus: { fire: 10, earth: 10 }, typeBonus: { healer: 10 } },
    { id: 'hakaikousen', name: '破壊光線', kind: 'attack', power: 80, target: 'single', recoilPct: 30, elemBonus: { fire: 15, earth: 10 }, typeBonus: { healer: 15 } },
    { id: 'gekirin', name: '逆鱗', kind: 'attack', power: 50, target: 'single', elemBonus: { fire: 15, earth: 10 }, typeBonus: { healer: 15 }, effects: [{ type: 'status', to: 'self', status: 'confuse', chance: 40 }], desc: '40%で自分がこんらん' },
    { id: 'ikaku', name: '威嚇の咆哮', kind: 'status', target: 'allEnemies', effects: [{ type: 'mod', to: 'target', stat: 'atkPct', value: -15, turns: 2 }], desc: '敵全体の攻撃力-15% (2ターン)' },
    // メタモ (相手に変身)
    { id: 'henshin', name: 'へんげ', kind: 'special', target: 'single', effects: [{ type: 'transform', to: 'self', char: '@target' }, { type: 'spinAgain' }], desc: '選んだ相手と同じキャラに変身して、もう一回 (ルーレットも相手のものになる)' },
    { id: 'purupuru', name: 'ぷるぷる', kind: 'guard', target: 'self', effects: [{ type: 'mod', to: 'self', stat: 'evadePct', value: 30, turns: 2 }], desc: '2ターン回避率+30%' },
    { id: 'buttukari', name: 'ぶつかり', kind: 'attack', power: 25, target: 'single' },
    // ネボスケ (寝てばかりの大食い)
    { id: 'heavybody', name: 'ヘビーボディ', kind: 'attack', power: 35, target: 'single', elemBonus: { thunder: 10, fire: 10 }, typeBonus: { attacker: 15 } },
    { id: 'inemuri', name: '居眠り', kind: 'heal', target: 'self', effects: [{ type: 'cure', to: 'self' }, { type: 'heal', to: 'self', pct: 25 }, { type: 'status', to: 'self', status: 'sleep', turns: 1 }], desc: '状態異常を治し、最大HPの25%回復。そのあと1ターン眠る' },
    { id: 'ibiki', name: 'いびき地震', kind: 'attack', power: 22, target: 'allEnemies', elemBonus: { thunder: 10, fire: 5 }, typeBonus: { attacker: 10 } },
    { id: 'akubi', name: '大あくび', kind: 'status', target: 'single', effects: [{ type: 'status', to: 'target', status: 'sleep', chance: 50 }], desc: '50%で相手をねむりにする' },
    // ミライ (念・未来予知)
    { id: 'nenpa', name: '念波', kind: 'attack', power: 26, target: 'allEnemies', elemBonus: { light: 10, earth: 10 }, typeBonus: { defender: 10 } },
    { id: 'miraiyochi', name: '未来予知', kind: 'status', target: 'single', color: '#ff7ad9', effects: [{ type: 'status', to: 'target', status: 'future' }], desc: '2ターン後に相手へ55ダメージ' },
    { id: 'nendobarrier', name: '念動バリア', kind: 'guard', target: 'self', effects: [{ type: 'mod', to: 'self', stat: 'nullifyBelow', value: 25, turns: 2 }], desc: '2ターン、25以下のダメージを無効' },
    { id: 'psychohou', name: 'サイコ砲', kind: 'attack', power: 50, target: 'single', elemBonus: { light: 15, earth: 10 }, typeBonus: { defender: 15 } },
    { id: 'fuuinnen', name: '封印の念', kind: 'status', target: 'single', effects: [{ type: 'mod', to: 'target', stat: 'healBlock', value: 1, turns: 3 }, { type: 'mod', to: 'target', stat: 'missWeightPct', value: 40, turns: 2 }], desc: '相手を回復封じ (3ターン) にし、ミスの区画を40%大きくする (2ターン)' },
    // ボムボール (速くて自爆する)
    { id: 'dengekiball', name: '電撃ボール', kind: 'attack', power: 30, target: 'single', elemBonus: { water: 10, wind: 10 }, typeBonus: { healer: 15 } },
    { id: 'korogarinige', name: '転がり逃げ', kind: 'status', target: 'self', effects: [{ type: 'mod', to: 'self', stat: 'speed', value: 2, turns: 3 }, { type: 'mod', to: 'self', stat: 'evadePct', value: 40, turns: 2 }], desc: 'すばやさ+2 (3ターン)・回避率+40% (2ターン)' },
    { id: 'jibaku', name: '大自爆', kind: 'attack', power: 70, target: 'allEnemies', elemBonus: { water: 10, wind: 5 }, typeBonus: { healer: 10 }, effects: [{ type: 'damage', to: 'self', power: 999 }], desc: '敵全体に70の大爆発。自分は倒れる' },
    { id: 'sparksanpu', name: 'スパーク散布', kind: 'attack', power: 22, target: 'allEnemies', elemBonus: { water: 10, wind: 5 }, typeBonus: { healer: 10 }, effects: [{ type: 'status', to: 'target', status: 'para', chance: 20 }], desc: '敵全体。20%でまひ' },
    // タマゴママ (みんなを癒やす)
    { id: 'tamagoumi', name: '卵産み', kind: 'heal', target: 'self', effects: [{ type: 'heal', to: 'self', pct: 25 }], desc: '最大HPの20%回復' },
    { id: 'minnakaifuku', name: 'みんなで回復', kind: 'heal', target: 'everyone', effects: [{ type: 'heal', to: 'target', amount: 20 }], desc: '全員 (敵も!) のHPを15回復' },
    { id: 'tamagobakudan', name: '卵爆弾', kind: 'attack', power: 35, target: 'randomEnemy', elemBonus: { dark: 10, psychic: 10 }, typeBonus: { trickster: 15 }, desc: 'ランダムな敵に投げる' },
    { id: 'houyou', name: '包容', kind: 'guard', target: 'self', effects: [{ type: 'mod', to: 'self', stat: 'regen', value: 8, turns: 3 }, { type: 'mod', to: 'self', stat: 'barrier', value: 25, turns: 3 }], desc: '3ターン毎ターン8回復・20のバリア' },
    // ツバサ (風・会心)
    { id: 'kyukouka', name: '急降下', kind: 'attack', power: 45, target: 'single', elemBonus: { grass: 15, psychic: 10 }, typeBonus: { healer: 15 } },
    { id: 'boufuu', name: '暴風', kind: 'attack', power: 28, target: 'allEnemies', elemBonus: { grass: 10, psychic: 5 }, typeBonus: { healer: 10 } },
    { id: 'oikaze', name: '追い風', kind: 'status', target: 'self', effects: [{ type: 'mod', to: 'self', stat: 'speed', value: 3, turns: 3 }, { type: 'mod', to: 'self', stat: 'critPct', value: 30, turns: 3 }], desc: '3ターン、すばやさ+3・会心率+30%' },
    { id: 'haneyasume', name: '羽休め', kind: 'heal', target: 'self', effects: [{ type: 'heal', to: 'self', amount: 30 }] },
    // トゲリン (トゲと挑発)
    { id: 'togesoukou', name: 'トゲ装甲', kind: 'guard', target: 'self', effects: [{ type: 'mod', to: 'self', stat: 'thorns', value: 12, turns: 3 }], desc: '3ターン、攻撃してきた相手に12ダメージ' },
    { id: 'harisenbon', name: '針千本', kind: 'attack', power: 17, hits: 3, target: 'single', elemBonus: { thunder: 5, fire: 10 }, typeBonus: { defender: 15 }, desc: '3回攻撃' },
    { id: 'chouhatsu', name: '挑発', kind: 'status', target: 'self', effects: [{ type: 'mod', to: 'self', stat: 'taunt', value: 1, turns: 2 }, { type: 'mod', to: 'self', stat: 'defFlat', value: 5, turns: 2 }], desc: '2ターン、敵は自分しか狙えない・被ダメ-5' },
    { id: 'dokubari', name: '毒針', kind: 'attack', power: 25, target: 'single', elemBonus: { thunder: 15, fire: 10 }, typeBonus: { defender: 15 }, effects: [{ type: 'status', to: 'target', status: 'poison', chance: 35 }], desc: '35%でどく' },
    // カゲロウ (隠れ身の忍び)
    { id: 'kakuremi', name: '隠れ身', kind: 'guard', target: 'self', effects: [{ type: 'mod', to: 'self', stat: 'stealth', value: 1, turns: 2 }], desc: '2ターン、狙われなくなる (全体攻撃は当たる)' },
    { id: 'kagenui', name: '影縫い', kind: 'attack', power: 30, target: 'single', elemBonus: { light: 15, psychic: 10 }, typeBonus: { healer: 15 }, effects: [{ type: 'mod', to: 'target', stat: 'speed', value: -3, turns: 3 }], desc: '相手のすばやさ-3 (3ターン)' },
    { id: 'ansatsu', name: '闇討ち', kind: 'attack', power: 35, target: 'single', elemBonus: { light: 15, psychic: 10 }, typeBonus: { healer: 20 }, effects: [{ type: 'damage', to: 'target', power: 25, cond: { targetHpBelowPct: 40 } }], desc: '相手のHPが40%以下なら追加25' },
    { id: 'makibishi', name: 'まきびし', kind: 'status', target: 'allEnemies', effects: [{ type: 'mod', to: 'target', stat: 'regen', value: -6, turns: 3 }], desc: '敵全体が3ターン、毎ターン6ダメージ (衰弱)' },

    // ===== 条件付きの範囲攻撃 (〇属性全員・〇タイプ全員) =====
    { id: 'noyaki', name: '野焼き', kind: 'attack', power: 40, target: 'group', groupElement: 'grass', desc: '草属性の敵全員に40' },
    { id: 'shoukanoame', name: '消火の雨', kind: 'attack', power: 40, target: 'group', groupElement: 'fire', desc: '炎属性の敵全員に40' },
    { id: 'kyusuinone', name: '吸水の根', kind: 'attack', power: 40, target: 'group', groupElement: 'water', desc: '水属性の敵全員に40' },
    { id: 'kandennet', name: '感電ネット', kind: 'attack', power: 40, target: 'group', groupElement: 'water', desc: '水属性の敵全員に40' },
    { id: 'jouka', name: '浄化の光', kind: 'attack', power: 40, target: 'group', groupElement: 'dark', desc: '闇属性の敵全員に40' },
    { id: 'mushibamu', name: '蝕む闇', kind: 'attack', power: 40, target: 'group', groupElement: 'light', desc: '光属性の敵全員に40' },
    { id: 'jishin', name: '地震', kind: 'attack', power: 40, target: 'group', groupElement: 'thunder', desc: '雷属性の敵全員に40' },
    { id: 'kogarashi', name: '木枯らし', kind: 'attack', power: 40, target: 'group', groupElement: 'grass', desc: '草属性の敵全員に40' },
    { id: 'nenbaku', name: '念縛', kind: 'attack', power: 40, target: 'group', groupElement: 'earth', desc: '地属性の敵全員に40' },
    { id: 'healergari', name: 'ヒーラー狩り', kind: 'attack', power: 45, target: 'group', groupType: 'healer', desc: 'ヒーラーの敵全員に45' },
    { id: 'yousaikuzushi', name: '要塞崩し', kind: 'attack', power: 45, target: 'group', groupType: 'defender', desc: 'ディフェンダーの敵全員に45' },
    { id: 'oshioki', name: 'お仕置き', kind: 'attack', power: 45, target: 'group', groupType: 'trickster', desc: 'トリックスターの敵全員に45' },
    { id: 'attackerfuuji', name: 'アタッカー封じ', kind: 'attack', power: 30, target: 'group', groupType: 'attacker', effects: [{ type: 'mod', to: 'target', stat: 'atkPct', value: -20, turns: 2 }], desc: 'アタッカーの敵全員に30・攻撃力-20% (2ターン)' },
  ],

  abilities: [
    { id: 'ganjou', name: '頑丈', trigger: 'battleStart', effects: [{ type: 'mod', to: 'self', stat: 'endure', value: 1, turns: 0 }], desc: '倒れそうな攻撃を1回だけHP1でこらえる' },
    { id: 'kuishinbo', name: '食いしん坊', trigger: 'turnEnd', effects: [{ type: 'heal', to: 'self', amount: 8 }], desc: '自分のターン終了時にHP3回復' },
    { id: 'surudoime', name: '鋭い目', trigger: 'battleStart', effects: [{ type: 'mod', to: 'self', stat: 'critPct', value: 15, turns: 0 }], desc: '会心率+15% (ずっと)' },
    { id: 'tetsunotoge', name: '鉄のトゲ', trigger: 'battleStart', effects: [{ type: 'mod', to: 'self', stat: 'thorns', value: 7, turns: 0 }], desc: '攻撃してきた相手に7ダメージ (ずっと)' },
    { id: 'jiai', name: '慈愛', trigger: 'battleStart', effects: [{ type: 'mod', to: 'self', stat: 'regen', value: 2, turns: 0 }], desc: '毎ターンHP2回復 (ずっと)' },
    { id: 'shinobi', name: '忍びの心得', trigger: 'battleStart', effects: [{ type: 'mod', to: 'self', stat: 'evadePct', value: 15, turns: 0 }], desc: '回避率+15% (ずっと)' },
    { id: 'kozakana', name: '小魚の根性', trigger: 'battleStart', effects: [{ type: 'mod', to: 'self', stat: 'endure', value: 1, turns: 0 }], desc: '大化けするまで粘れるよう、1回だけHP1でこらえる' },
    { id: 'seibi', name: '整備士', trigger: 'battleStart', effects: [{ type: 'attachGear', to: 'self', gear: 'gear_power' }], desc: 'バトル開始時からパワーギアをつけている' },
    { id: 'moka', name: '逆境の炎', trigger: 'onLowHp', lowHpPct: 50, once: true, effects: [{ type: 'mod', to: 'self', stat: 'atkPct', value: 30, turns: 0 }], desc: 'HPが50%以下になると攻撃力+30% (永続)' },
    { id: 'honoonokarada', name: '灼熱の体', trigger: 'onHit', chance: 30, effects: [{ type: 'status', to: 'attacker', status: 'burn' }], desc: '攻撃を受けると30%で相手をやけどにする' },
    { id: 'uruoi', name: '潤いの泉', trigger: 'turnEnd', effects: [{ type: 'heal', to: 'self', amount: 8 }], desc: '自分のターン終了時にHP3回復' },
    { id: 'kataikora', name: '鉄壁の甲羅', trigger: 'passive', passive: { nullifyBelow: 5 }, desc: '5以下のダメージを無効' },
    { id: 'kougousei', name: '光合成の恵み', trigger: 'onLowHp', lowHpPct: 40, once: true, effects: [{ type: 'heal', to: 'self', amount: 20 }, { type: 'cure', to: 'self' }], desc: 'HPが40%以下になると1度だけHP15回復・状態異常回復' },
    { id: 'rinpun', name: '毒鱗粉', trigger: 'onAttack', chance: 25, cond: { dealtAtLeast: 1 }, effects: [{ type: 'status', to: 'target', status: 'poison' }], desc: '攻撃を当てると25%で相手をどくにする' },
    { id: 'seidenki', name: '帯電ボディ', trigger: 'onHit', chance: 30, effects: [{ type: 'status', to: 'attacker', status: 'para' }], desc: '攻撃を受けると30%で相手をまひさせる' },
    { id: 'denkiengine', name: '失敗エンジン', trigger: 'onSpin', cond: { moveKind: 'miss' }, effects: [{ type: 'mod', to: 'self', stat: 'atkFlat', value: 15, turns: 0 }], desc: 'ミスを引くたびに攻撃力+15 (永続・重なる)' },
    { id: 'seinarukago', name: '聖なる加護', trigger: 'battleStart', effects: [{ type: 'mod', to: 'self', stat: 'barrier', value: 25, turns: 0 }], desc: 'バトル開始時に20のバリアを張る' },
    { id: 'kishi', name: '騎士の誇り', trigger: 'passive', passive: { immune: ['confuse', 'sleep'] }, desc: 'こんらん・ねむりにならない' },
    { id: 'kyuketsu', name: '吸血', trigger: 'onAttack', cond: { dealtAtLeast: 1 }, effects: [{ type: 'heal', to: 'self', ofDamagePct: 10 }], desc: '攻撃を当てると与ダメの10%回復' },
    { id: 'norowarebody', name: '呪われた身', trigger: 'onHit', chance: 35, effects: [{ type: 'mod', to: 'attacker', stat: 'atkPct', value: -20, turns: 2 }], desc: '攻撃を受けると35%で相手の攻撃力-20% (2ターン)' },
    { id: 'saigonoichigeki', name: '最後の一撃', trigger: 'onDowned', effects: [{ type: 'mod', to: 'self', stat: 'atkPct', value: 50, turns: 0 }], desc: 'たおれかけると最後の行動の攻撃力+50%' },
    // 変わり種キャラ用
    { id: 'dojikko', name: 'ドジっ子', trigger: 'onSpin', cond: { moveKind: 'miss' }, chance: 50, effects: [{ type: 'spinAgain' }], desc: 'ミスを引いても50%でもう一回回せる' },
    { id: 'bakenokawa', name: '身代わり人形', trigger: 'battleStart', effects: [{ type: 'mod', to: 'self', stat: 'guard', value: 1, turns: 0 }], desc: '最初に受ける攻撃を1回だけ無効にする' },
    { id: 'kyoun', name: '強運', trigger: 'battleStart', effects: [{ type: 'mod', to: 'self', stat: 'luck', value: 1, turns: 0 }], desc: 'バトル開始時にミス回避🍀を1回ぶん持っている' },
    { id: 'timeparadox', name: 'タイムパラドックス', trigger: 'onDowned', effects: [{ type: 'mod', to: 'self', stat: 'extraSpins', value: 1, turns: 1 }], desc: 'たおれかけると、最後のターンが2回行動になる' },
    { id: 'dokasen', name: '導火線', trigger: 'onHit', chance: 30, cond: { dealtAtLeast: 1 }, effects: [{ type: 'status', to: 'attacker', status: 'bomb' }], desc: '攻撃を受けると30%で相手にばくだんを仕掛け返す' },
    { id: 'fukutsu', name: '不屈の闘志', trigger: 'onHit', chance: 40, cond: { dealtAtLeast: 1 }, effects: [{ type: 'mod', to: 'self', stat: 'nextPower', value: 20, turns: 0 }], desc: '攻撃を受けると40%で次の攻撃の威力+20' },
    { id: 'itazura', name: 'いたずら好き', trigger: 'onHit', chance: 30, effects: [{ type: 'invertMods', to: 'attacker' }], desc: '攻撃を受けると30%で相手のバフとデバフを逆にする' },
  ],

  chars: [
    { id: 'flamelio', name: 'フレイムリオ', icon: '🦁', color: '#ff7a45', element: 'fire', type: 'attacker', speed: 3, mark: 'dot', baseHp: 120, abilities: ['moka'],
      moves: [{ move: 'noyaki', weight: 3 }, { move: 'hinoko', weight: 6 }, { move: 'flareblast', weight: 4 }, { move: 'neppu', weight: 5 }, { move: 'hoeru', weight: 3 }, { move: 'miss', weight: 3 }],
      desc: '一撃が重い炎の獅子。ピンチで燃え上がる' },
    { id: 'kagura', name: 'カグラ', icon: '🦊', color: '#ff9a5a', element: 'fire', type: 'trickster', speed: 4, mark: 'star', baseHp: 105, abilities: ['honoonokarada'],
      moves: [{ move: 'yousaikuzushi', weight: 3 }, { move: 'onibi', weight: 4 }, { move: 'kaenguruma', weight: 5 }, { move: 'madowashi', weight: 4 }, { move: 'kitsunebi', weight: 4 }, { move: 'youko', weight: 2 }, { move: 'miss', weight: 2 }],
      desc: 'やけど・こんらんで場をかき乱す狐' },
    { id: 'aqualin', name: 'アクアリン', icon: '🐬', color: '#4aa8ff', element: 'water', type: 'healer', speed: 2, mark: 'dot', baseHp: 105, abilities: ['uruoi'],
      moves: [{ move: 'shoukanoame', weight: 3 }, { move: 'mizudeppo', weight: 5 }, { move: 'shizuku', weight: 3 }, { move: 'bubbleshield', weight: 4 }, { move: 'dakuryu', weight: 4 }, { move: 'miss', weight: 5 }],
      desc: '回復とバリアで粘る長期戦タイプ' },
    { id: 'tidoron', name: 'タイドロン', icon: '🐢', color: '#3a7fd0', element: 'water', type: 'defender', speed: 1, mark: 'star', baseHp: 105, abilities: ['kataikora'],
      moves: [{ move: 'attackerfuuji', weight: 3 }, { move: 'hydrocannon', weight: 3 }, { move: 'karani', weight: 2 }, { move: 'noshikakari', weight: 3 }, { move: 'reitobeam', weight: 3 }, { move: 'naminori', weight: 4 }, { move: 'miss', weight: 6 }],
      desc: '小さなダメージを弾く甲羅の要塞' },
    { id: 'leafgard', name: 'リーフガルド', icon: '🌳', color: '#4cc66a', element: 'grass', type: 'defender', speed: 1, mark: 'dot', baseHp: 105, abilities: ['kougousei'],
      moves: [{ move: 'kyusuinone', weight: 3 }, { move: 'tsurunomuchi', weight: 4 }, { move: 'yadorigi', weight: 4 }, { move: 'nemurigona', weight: 3 }, { move: 'woodhammer', weight: 3 }, { move: 'happacutter', weight: 4 }, { move: 'miss', weight: 3 }],
      desc: '吸収と回復でしぶとく生き残る大樹' },
    { id: 'hanami', name: 'ハナミ', icon: '🌸', color: '#ff8ac8', element: 'grass', type: 'trickster', speed: 3, mark: 'star', baseHp: 110, abilities: ['rinpun'],
      moves: [{ move: 'yousaikuzushi', weight: 3 }, { move: 'dokunokona', weight: 5 }, { move: 'hanafubuki', weight: 4 }, { move: 'amaikaori', weight: 4 }, { move: 'hanabira', weight: 6 }, { move: 'miss', weight: 2 }],
      desc: 'どくとデバフでじわじわ削る花の妖精' },
    { id: 'volty', name: 'ボルティ', icon: '🐹', color: '#f5c518', element: 'thunder', type: 'trickster', speed: 5, mark: 'dot', baseHp: 105, abilities: ['seidenki'],
      moves: [{ move: 'kandennet', weight: 3 }, { move: 'denkishock', weight: 6 }, { move: 'houden', weight: 5 }, { move: 'kousoku', weight: 4 }, { move: 'kaminari', weight: 2 }, { move: 'miss', weight: 4 }],
      desc: '最速でまひをばらまく電気ネズミ' },
    { id: 'raiga', name: 'ライガ', icon: '🐯', color: '#e8b400', element: 'thunder', type: 'attacker', speed: 4, mark: 'dot', baseHp: 110, abilities: ['denkiengine'],
      moves: [{ move: 'healergari', weight: 3 }, { move: 'wildvolt', weight: 4 }, { move: 'kaminarinokiba', weight: 7 }, { move: 'raimei', weight: 4 }, { move: 'juden', weight: 2 }, { move: 'miss', weight: 4 }],
      desc: 'ミスが多いがミスるほど強くなる。ディフェンダー・ヒーラーを狩る単体火力' },
    { id: 'lumina', name: 'ルミナ', icon: '🦄', color: '#ffe08a', element: 'light', type: 'healer', speed: 2, mark: 'star', baseHp: 110, abilities: ['seinarukago'],
      moves: [{ move: 'jouka', weight: 3 }, { move: 'hikarinoya', weight: 4 }, { move: 'iyashinohikari', weight: 4 }, { move: 'holyray', weight: 4 }, { move: 'seiiki', weight: 2 }, { move: 'flash', weight: 4 }, { move: 'miss', weight: 3 }],
      desc: 'バリアと聖域で攻撃を寄せ付けない' },
    { id: 'saber', name: 'セイバー', icon: '⚔️', color: '#d8d8ff', element: 'light', type: 'balance', speed: 3, mark: 'star', baseHp: 115, abilities: ['kishi'],
      moves: [{ move: 'oshioki', weight: 3 }, { move: 'seiken', weight: 5 }, { move: 'iatsu', weight: 4 }, { move: 'mikiri', weight: 3 }, { move: 'gigaslash', weight: 4 }, { move: 'miss', weight: 5 }],
      desc: '★の騎士。●に強く、トリックスターやギャンブラーを斬る' },
    { id: 'nox', name: 'ノクス', icon: '🦇', color: '#9a6cff', element: 'dark', type: 'attacker', speed: 4, mark: 'dot', baseHp: 105, abilities: ['kyuketsu'],
      moves: [{ move: 'mushibamu', weight: 3 }, { move: 'shadowclaw', weight: 3 }, { move: 'nightburst', weight: 3 }, { move: 'akumu', weight: 3 }, { move: 'yumekui', weight: 3 }, { move: 'koumorinomure', weight: 4 }, { move: 'miss', weight: 5 }],
      desc: '眠らせて喰らう吸血コウモリ' },
    { id: 'shade', name: 'シェイド', icon: '👻', color: '#7a5cc0', element: 'dark', type: 'trickster', speed: 5, mark: 'star', baseHp: 105, abilities: ['norowarebody', 'saigonoichigeki'],
      moves: [{ move: 'mushibamu', weight: 3 }, { move: 'ayashiihikari', weight: 4 }, { move: 'shadowball', weight: 6 }, { move: 'noroi', weight: 2 }, { move: 'kagebunshin', weight: 3 }, { move: 'ghostparade', weight: 4 }, { move: 'miss', weight: 2 }],
      desc: 'のろいとこんらんで翻弄するゴースト' },

    // ===== 変わり種 =====
    { id: 'ponkotsu', name: 'ポンコツ', icon: '🤖', color: '#9fb4c8', element: 'thunder', type: 'balance', speed: 2, mark: 'dot', baseHp: 115, abilities: ['dojikko'],
      moves: [{ move: 'kandennet', weight: 3 }, { move: 'yakekuso', weight: 4 }, { move: 'garakuta', weight: 5 }, { move: 'overheat', weight: 2 }, { move: 'shuuri', weight: 3 }, { move: 'miss', weight: 7 }],
      desc: 'ミスだらけのドジロボ。ミスするほど「やけくそビーム」が強くなる' },
    { id: 'mimic', name: 'ミミック', icon: '🎭', color: '#c07ad8', element: 'dark', type: 'trickster', speed: 3, mark: 'star', baseHp: 105, abilities: ['bakenokawa'],
      moves: [{ move: 'yubiwofuru', weight: 7 }, { move: 'monomane', weight: 4 }, { move: 'odorokasu', weight: 5 }, { move: 'marunomi', weight: 4 }, { move: 'miss', weight: 4 }],
      desc: '何が出るかわからない「気まぐれタクト」と、相手の技を盗む「コピーキャット」' },
    { id: 'dice', name: 'ダイス', icon: '🎲', color: '#ffd24a', element: 'light', type: 'gambler', speed: 3, mark: 'star', baseHp: 105, abilities: ['kyoun'],
      moves: [{ move: 'jouka', weight: 3 }, { move: 'allin', weight: 4 }, { move: 'daigyakuten', weight: 2 }, { move: 'luckycoin', weight: 3 }, { move: 'diceshot', weight: 6 }, { move: 'baramakidice', weight: 4 }, { move: 'miss', weight: 2 }],
      desc: '一発逆転のギャンブラー。「大逆転ルーレット」で全員のHPをかき混ぜる' },
    { id: 'chrono', name: 'クロノ', icon: '⏰', color: '#6fd0ff', element: 'water', type: 'balance', speed: 4, mark: 'star', baseHp: 110, abilities: ['timeparadox'],
      moves: [{ move: 'shoukanoame', weight: 3 }, { move: 'timeaccel', weight: 4 }, { move: 'jikandorobo', weight: 4 }, { move: 'tokiwotomeru', weight: 1 }, { move: 'chikutaku', weight: 5 }, { move: 'timewave', weight: 4 }, { move: 'miss', weight: 3 }],
      desc: '時をあやつる。「タイムアクセル」で2回行動、バフも盗む' },
    { id: 'bomber', name: 'ボマー', icon: '💣', color: '#ff9340', element: 'fire', type: 'trickster', speed: 2, mark: 'dot', baseHp: 115, abilities: ['dokasen'],
      moves: [{ move: 'noyaki', weight: 3 }, { move: 'bombset', weight: 5 }, { move: 'bombpass', weight: 4 }, { move: 'daibakuhatsu', weight: 2 }, { move: 'hibana', weight: 7 }, { move: 'miss', weight: 3 }],
      desc: 'ばくだんを仕掛け、押し付け合いの大騒ぎを起こす爆弾魔' },
    { id: 'ryu', name: 'リュウ', icon: '🥋', color: '#6ccf7a', element: 'grass', type: 'attacker', speed: 3, mark: 'dot', baseHp: 115, abilities: ['fukutsu'],
      moves: [{ move: 'healergari', weight: 3 }, { move: 'tamepunch', weight: 6 }, { move: 'kiaidame', weight: 2 }, { move: 'hissatsu', weight: 4 }, { move: 'hoshikudaki', weight: 4 }, { move: 'mikiri', weight: 2 }, { move: 'miss', weight: 3 }],
      desc: '使うたびに強くなる「ためパンチ」の拳士。ディフェンダーの天敵' },
    { id: 'joker', name: 'ジョーカー', icon: '🃏', color: '#e86a9a', element: 'dark', type: 'trickster', speed: 4, mark: 'star', baseHp: 105, abilities: ['itazura'],
      moves: [{ move: 'yousaikuzushi', weight: 3 }, { move: 'abekobe', weight: 3 }, { move: 'surikae', weight: 2 }, { move: 'mirrorcoat', weight: 3 }, { move: 'trumpnage', weight: 6 }, { move: 'cardshower', weight: 4 }, { move: 'miss', weight: 3 }],
      desc: 'HP入れ替え・バフ反転・反射。ピンチほど何をするかわからない' },

    // ===== 進化するキャラ =====
    { id: 'chibidora', name: 'チビドラ', icon: '🐣', color: '#ffb35a', element: 'fire', type: 'balance', speed: 3, mark: 'dot', baseHp: 110, abilities: [],
      moves: [{ move: 'noyaki', weight: 3 }, { move: 'hinoko', weight: 5 }, { move: 'taiatari', weight: 6 }, { move: 'shinka', weight: 6 }, { move: 'miss', weight: 4 }],
      desc: '「覚醒」を引くとドラグーンに進化して一気に強くなる' },
    { id: 'dragoon', name: 'ドラグーン', icon: '🐉', color: '#ff6a3d', element: 'fire', type: 'attacker', speed: 3, mark: 'dot', baseHp: 110, abilities: ['moka'], hidden: true,
      moves: [{ move: 'noyaki', weight: 3 }, { move: 'ryunoibuki', weight: 4 }, { move: 'dragonclaw', weight: 6 }, { move: 'flaredrive', weight: 4 }, { move: 'hoeru', weight: 3 }, { move: 'miss', weight: 4 }],
      desc: 'チビドラの進化形 (セットアップでは選べない)' },
    { id: 'mechanic', name: 'メカニック', icon: '🔧', color: '#9fb4c8', element: 'thunder', type: 'trickster', speed: 3, mark: 'star', baseHp: 110, abilities: ['seibi'],
      moves: [{ move: 'yousaikuzushi', weight: 3 }, { move: 'gearup', weight: 5 }, { move: 'gearcurse', weight: 5 }, { move: 'spanner', weight: 4 }, { move: 'gearbreak', weight: 4 }, { move: 'miss', weight: 3 }],
      desc: '自分に良いギア、相手に悪いギアをつけるギア使い' },

    // ===== バトエンのいろいろなキャラを参考にした新キャラ =====
    { id: 'ganseki', name: 'ガンセキ', icon: '🪨', color: '#c49a5a', element: 'earth', type: 'defender', speed: 1, mark: 'dot', baseHp: 110, abilities: ['ganjou'],
      moves: [{ move: 'jishin', weight: 3 }, { move: 'rakuseki', weight: 4 }, { move: 'jiware', weight: 4 }, { move: 'korogari', weight: 5 }, { move: 'iwakamae', weight: 3 }, { move: 'miss', weight: 5 }],
      desc: '頑丈な岩。挑発して攻撃を引き受け、転がるほど強くなる' },
    { id: 'mozo', name: 'モゾ', icon: '🐛', color: '#9ed36a', element: 'grass', type: 'balance', speed: 2, mark: 'star', baseHp: 105, abilities: [],
      moves: [{ move: 'itohaki', weight: 5 }, { move: 'kajiru', weight: 7 }, { move: 'dappi', weight: 6 }, { move: 'miss', weight: 6 }],
      desc: '「脱皮」でサナギン、「羽化」でヒラリスへ。3段階に進化する' },
    { id: 'saNagin', name: 'サナギン', icon: '🪺', color: '#b8c47a', element: 'grass', type: 'defender', speed: 1, mark: 'star', baseHp: 105, abilities: [], hidden: true,
      moves: [{ move: 'katakunaru', weight: 7 }, { move: 'uka', weight: 9 }, { move: 'jittotaeru', weight: 5 }, { move: 'miss', weight: 3 }],
      desc: 'モゾの進化形。硬くなって羽化を待つ (セットアップでは選べない)' },
    { id: 'hirarisu', name: 'ヒラリス', icon: '🦋', color: '#8fe3c0', element: 'wind', type: 'trickster', speed: 5, mark: 'star', baseHp: 105, abilities: [], hidden: true,
      moves: [{ move: 'kogarashi', weight: 3 }, { move: 'rinpunstorm', weight: 4 }, { move: 'kazenomai', weight: 4 }, { move: 'kyumitsu', weight: 6 }, { move: 'itohaki', weight: 3 }, { move: 'miss', weight: 4 }],
      desc: 'サナギンの進化形。鱗粉の嵐と回避で舞う (セットアップでは選べない)' },
    { id: 'pichipichi', name: 'ピチピチ', icon: '🐟', color: '#ff9a6a', element: 'water', type: 'balance', speed: 4, mark: 'dot', baseHp: 95, abilities: ['kozakana'],
      moves: [{ move: 'haneru', weight: 10 }, { move: 'taiatari', weight: 9 }, { move: 'daikakusei', weight: 5 }],
      desc: 'ほとんど跳ねるだけの弱い魚。「大覚醒」を引けば最強クラスのリヴァイアに大化け' },
    { id: 'riviah', name: 'リヴァイア', icon: '🐍', color: '#3a7fd0', element: 'water', type: 'attacker', speed: 4, mark: 'dot', baseHp: 95, abilities: [], hidden: true,
      moves: [{ move: 'shoukanoame', weight: 3 }, { move: 'ouzu', weight: 4 }, { move: 'hakaikousen', weight: 3 }, { move: 'gekirin', weight: 6 }, { move: 'ikaku', weight: 4 }, { move: 'miss', weight: 4 }],
      desc: 'ピチピチが大化けした姿 (セットアップでは選べない)' },
    { id: 'metamo', name: 'メタモ', icon: '🫧', color: '#c0a0ff', element: 'psychic', type: 'balance', speed: 3, mark: 'star', baseHp: 110, abilities: [],
      moves: [{ move: 'henshin', weight: 12 }, { move: 'purupuru', weight: 5 }, { move: 'buttukari', weight: 3 }, { move: 'miss', weight: 4 }],
      desc: '「へんげ」で選んだ相手と同じキャラに変身する。変身後は相手のルーレットで戦う' },
    { id: 'nebosuke', name: 'ネボスケ', icon: '😴', color: '#6a8a9a', element: 'earth', type: 'defender', speed: 1, mark: 'dot', baseHp: 100, abilities: ['kuishinbo'],
      moves: [{ move: 'attackerfuuji', weight: 3 }, { move: 'heavybody', weight: 5 }, { move: 'inemuri', weight: 2 }, { move: 'ibiki', weight: 5 }, { move: 'akubi', weight: 4 }, { move: 'miss', weight: 5 }],
      desc: 'HPが多い大食い。居眠りで大回復するが、その間は動けない' },
    { id: 'mirai', name: 'ミライ', icon: '🔮', color: '#ff7ad9', element: 'psychic', type: 'trickster', speed: 4, mark: 'star', baseHp: 110, abilities: [],
      moves: [{ move: 'nenbaku', weight: 3 }, { move: 'nenpa', weight: 5 }, { move: 'miraiyochi', weight: 5 }, { move: 'nendobarrier', weight: 2 }, { move: 'psychohou', weight: 4 }, { move: 'fuuinnen', weight: 2 }, { move: 'miss', weight: 3 }],
      desc: '未来予知で時間差攻撃。回復封じや不運のデバフも使う' },
    { id: 'bomball', name: 'ボムボール', icon: '💥', color: '#ff5a5a', element: 'thunder', type: 'attacker', speed: 6, mark: 'dot', baseHp: 115, abilities: [],
      moves: [{ move: 'kandennet', weight: 3 }, { move: 'dengekiball', weight: 7 }, { move: 'korogarinige', weight: 4 }, { move: 'jibaku', weight: 1 }, { move: 'sparksanpu', weight: 7 }, { move: 'miss', weight: 2 }],
      desc: '一番速い。まれに「大自爆」で敵全体を巻き込んで自分も倒れる' },
    { id: 'tamagomama', name: 'タマゴママ', icon: '🥚', color: '#ffe0c0', element: 'light', type: 'healer', speed: 2, mark: 'star', baseHp: 110, abilities: ['jiai'],
      moves: [{ move: 'oshioki', weight: 3 }, { move: 'tamagoumi', weight: 5 }, { move: 'minnakaifuku', weight: 3 }, { move: 'tamagobakudan', weight: 5 }, { move: 'houyou', weight: 4 }, { move: 'miss', weight: 4 }],
      desc: '回復のプロ。「みんなで回復」は敵まで回復してしまう' },
    { id: 'tsubasa', name: 'ツバサ', icon: '🦅', color: '#8fe3c0', element: 'wind', type: 'attacker', speed: 5, mark: 'dot', baseHp: 110, abilities: ['surudoime'],
      moves: [{ move: 'kogarashi', weight: 3 }, { move: 'kyukouka', weight: 5 }, { move: 'boufuu', weight: 6 }, { move: 'oikaze', weight: 4 }, { move: 'haneyasume', weight: 3 }, { move: 'miss', weight: 3 }],
      desc: '追い風で速さと会心率を上げて急降下する猛禽' },
    { id: 'togerin', name: 'トゲリン', icon: '🦔', color: '#b07a4a', element: 'earth', type: 'trickster', speed: 2, mark: 'star', baseHp: 115, abilities: ['tetsunotoge'],
      moves: [{ move: 'jishin', weight: 3 }, { move: 'togesoukou', weight: 4 }, { move: 'harisenbon', weight: 4 }, { move: 'chouhatsu', weight: 3 }, { move: 'dokubari', weight: 6 }, { move: 'miss', weight: 4 }],
      desc: '殴ると痛いトゲの塊。挑発して攻撃を集め、トゲで返す' },
    { id: 'kagerou', name: 'カゲロウ', icon: '🥷', color: '#5a5a7a', element: 'dark', type: 'attacker', speed: 5, mark: 'dot', baseHp: 100, abilities: ['shinobi'],
      moves: [{ move: 'healergari', weight: 3 }, { move: 'kakuremi', weight: 4 }, { move: 'kagenui', weight: 4 }, { move: 'ansatsu', weight: 6 }, { move: 'makibishi', weight: 4 }, { move: 'miss', weight: 3 }],
      desc: '隠れ身で狙われなくなり、弱った相手を闇討ちする忍び' },
  ],

  // ギア: キャラのルーレットの後に毎ターン回る小さなルーレット。1人1つまで
  gears: [
    { id: 'gear_power', name: 'パワーギア', icon: '💪', color: '#ff9a5a', kind: 'good', turns: 0, moves: [{ move: 'g_punch', weight: 3 }, { move: 'g_charge', weight: 1 }, { move: 'g_nothing', weight: 2 }], desc: '追加でパンチ。たまに攻撃力アップ' },
    { id: 'gear_heal', name: 'ヒールギア', icon: '💚', color: '#5fd38a', kind: 'good', turns: 0, moves: [{ move: 'g_heal', weight: 3 }, { move: 'g_nothing', weight: 2 }], desc: '毎ターン少し回復' },
    { id: 'gear_shield', name: 'シールドギア', icon: '🛡', color: '#5aa9f0', kind: 'good', turns: 0, moves: [{ move: 'g_shield', weight: 3 }, { move: 'g_nothing', weight: 2 }], desc: '毎ターン小さなバリア' },
    { id: 'gear_storm', name: 'ストームギア', icon: '🌪', color: '#c0a0ff', kind: 'good', turns: 0, moves: [{ move: 'g_storm', weight: 3 }, { move: 'g_nothing', weight: 2 }], desc: '追加で敵全体に15' },
    { id: 'gear_poison', name: 'どくギア', icon: '☠', color: '#b05cf0', kind: 'bad', turns: 4, moves: [{ move: 'g_poison', weight: 3 }, { move: 'g_poison2', weight: 1 }, { move: 'g_nothing', weight: 2 }], desc: '4ターンの間、毎ターン自分にダメージ' },
    { id: 'gear_sleepy', name: 'ねむけギア', icon: '💤', color: '#9aa7c7', kind: 'bad', turns: 4, moves: [{ move: 'g_doze', weight: 1 }, { move: 'g_nothing', weight: 3 }], desc: '4ターンの間、たまにねむってしまう' },
    { id: 'gear_rust', name: 'さびギア', icon: '🔩', color: '#b07a4a', kind: 'bad', turns: 4, moves: [{ move: 'g_rust', weight: 2 }, { move: 'g_nothing', weight: 2 }], desc: '4ターンの間、たまに攻撃力ダウン' },
  ],

  // きりふだ: 1試合に1回だけ、キャラのルーレットの代わりに回せる
  items: [
    { id: 'item_hero', name: 'ヒーローのきりふだ', icon: '🦸', color: '#ffcf3a', moves: [{ move: 'k_fullheal', weight: 1 }, { move: 'k_meteor', weight: 1 }, { move: 'k_finisher', weight: 1 }], desc: '大回復・全体45・威力90のどれか' },
    { id: 'item_guard', name: 'まもりのきりふだ', icon: '🏰', color: '#5aa9f0', moves: [{ move: 'k_fortress', weight: 2 }, { move: 'k_fullheal', weight: 1 }], desc: '守りを固める' },
    { id: 'item_chaos', name: 'どんでんのきりふだ', icon: '🌀', color: '#c07ad8', moves: [{ move: 'k_chaos', weight: 1 }, { move: 'k_average', weight: 1 }], desc: 'ピンチの時の大逆転用' },
    { id: 'item_time', name: 'ときのきりふだ', icon: '⏳', color: '#6fd0ff', moves: [{ move: 'k_timestop', weight: 2 }, { move: 'k_meteor', weight: 1 }], desc: '行動回数を増やす' },
    { id: 'item_gear', name: 'ギアのきりふだ', icon: '⚙', color: '#9fb4c8', moves: [{ move: 'k_goodgear', weight: 1 }, { move: 'k_curseall', weight: 1 }], desc: '自分に良いギア、または敵全員に悪いギア' },
  ],
};
